AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  submit-deepracer-model-app

  Sample SAM Template for submit-deepracer-model-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  ModelArn:
    Type: String
    Description: The ARN of the DeepRacer model that will be submitted by a job
  LeaderboardArn:
    Type: String
    Description: The ARN of the Virtual Circuit race where the model will be submitted

Resources:
  SubmitModelFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - deepracer:ListLeaderboards
                - deepracer:GetModel
                - deepracer:ListModels
                - deepracer:GetLeaderboard
                - deepracer:CreateLeaderboardSubmission
                - deepracer:GetLatestUserSubmission
              Resource: '*'
      Events:
        ScheduledFunction:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
            Input: !Sub '{"ModelArn": "${ModelArn}","LeaderboardArn": "${LeaderboardArn}"}'
    Metadata:
      DockerTag: python3.7-v1
      DockerContext: ./submit_model
      Dockerfile: Dockerfile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SubmitModelFunction:
    Description: "Submit Model Function Lambda Function ARN"
    Value: !GetAtt SubmitModelFunction.Arn
  SubmitModelFunctionIamRole:
    Description: "Implicit IAM Role created for the Lambda function"
    Value: !GetAtt SubmitModelFunctionRole.Arn
